CREATE CONSTRAINT IF NOT EXISTS
ON (p:Person)
ASSERT p.name IS NOT NULL;

CREATE CONSTRAINT IF NOT EXISTS
ON (p:Person)
ASSERT p.name IS UNIQUE;

CREATE CONSTRAINT IF NOT EXISTS
ON (c:Country)
ASSERT c.name IS NOT NULL;

CREATE CONSTRAINT IF NOT EXISTS
ON (c:Country)
ASSERT c.name IS UNIQUE;

CREATE CONSTRAINT IF NOT EXISTS
ON (s:Sport)
ASSERT s.name IS NOT NULL;

CREATE CONSTRAINT IF NOT EXISTS
ON (s:Sport)
ASSERT s.name IS UNIQUE;